import type { Metadata } from "next";
import { Fraunces, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  display: "swap",
  axes: ["SOFT", "WONK", "opsz"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

/**
 * Metadata for the application (SEO, etc.).
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root Layout component for the Next.js application.
 * Defines the global HTML structure, fonts, and providers (like Toaster).
 *
 * @param props - Props for the layout.
 * @param props.children - The child components to render.
 * @returns The rendered HTML document.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fraunces.variable} ${jetbrainsMono.variable} antialiased font-mono bg-background text-foreground selection:bg-primary/20`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
